name: Build and Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Source code
      run: pwd

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.Access_key }}
        aws-secret-access-key: ${{ secrets.Secret_access_key }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build, tag, and push Docker image
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k5u0o7b3
        docker build -t pacman .
        docker tag pacman:latest public.ecr.aws/k5u0o7b3/pacman:latest
        docker push public.ecr.aws/k5u0o7b3/pacman:latest
